env:
  browser: true
  es6: true
  node: true
  jest: true

extends:
  # - prettier
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - google
  - next/core-web-vitals
  - plugin:tailwindcss/recommended
  - plugin:eslint-plugin-prettier/recommended

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - '@typescript-eslint'
  # - prettier

rules:
  prettier/prettier:
    - warn
    - usePrettierrc: true

  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: '^[_]+$'
      argsIgnorePattern: '^[_]+$'
      ignoreRestSiblings: true

  # Needs to disable local no-unused-vars for this rule to work properly
  no-unused-vars:
    - off

  '@typescript-eslint/indent':
    - error
    - 2
    - ignoredNodes:
        - TSTypeParameterInstantiation
      MemberExpression: 1

  # Needs to disable local indent for this rule to work properly
  indent:
    - off

  linebreak-style:
    - error
    - unix

  max-len:
    - error
    - code: 119

  no-console:
    - error
    - allow:
        - warn
        - error

  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
      pathGroups:
        - pattern: react
          group: external
          position: before
      pathGroupsExcludedImportTypes:
        - react
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

  import/newline-after-import:
    - error
    # - count: 2

  object-curly-spacing: off
  # comma-spacing: off

  '@typescript-eslint/object-curly-spacing':
    - error
    - never

  semi:
    - off

  '@typescript-eslint/semi':
    - error

  '@typescript-eslint/explicit-module-boundary-types':
    - off

  '@typescript-eslint/no-explicit-any':
    - off

  '@typescript-eslint/explicit-function-return-type':
    - off

  space-in-parens:
    - error
    - never

  # Typescript will perform this checkno need for React to check it
  react/prop-types:
    - off

  react/jsx-closing-bracket-location: off
  react/jsx-closing-tag-location: off
  react/jsx-curly-spacing: off
  react/jsx-equals-spacing: off
  react/jsx-first-prop-new-line: off
  react/jsx-indent: off
  react/jsx-indent-props: off
  react/jsx-max-props-per-line: off
  react/jsx-tag-spacing: off
  react/jsx-wrap-multilines: off

  # react/jsx-tag-spacing:
  #   - error
  #   - beforeSelfClosing: never

  # Most of the dependencies are fine getting the initial value only
  react-hooks/exhaustive-deps:
    - warn

  require-jsdoc:
    - off

  tailwindcss/classnames-order:
    - error

settings:
  react:
    version: detect
