# Required pipeline level variables:
# - `MONGODB_URI`: For storing test data for SSG for next.js
# - `AZ_DEVOPS_DISCORD_WEBHOOK`: For sending out deployment status update in Discord
pool:
  vmImage: windows-latest

resources:
  repositories:
    - repository: scraper
      type: github
      endpoint: RaenonX-PokemonSleep
      name: RaenonX-PokemonSleep/pokemon-sleep-scraper

variables:
  - template: variables/main.yml
  - template: variables/checkout-and-cache.yml
  - template: variables/run-scraper.yml

stages:
- stage: Preparation
  jobs:
    - job: LintTSC
      displayName: Lint / TSC
      dependsOn: []
      steps:
      - template: templates/checkout-and-cache.yml

      - script: yarn run tsc
        displayName: 'Check TypeScript'

      - script: yarn run lint
        displayName: 'Lint Source'

      - script: yarn run lint:css
        displayName: 'Lint CSS'

    - job: Test
      displayName: Test
      dependsOn: []
      steps:
        - template: templates/checkout-and-cache.yml

        - script: yarn run test:ci
          displayName: 'Test Source'

    - job: Data
      displayName: Fetch Data
      dependsOn: []
      steps:
        - template: templates/run-scraper.yml

- stage: Build
  displayName: Build
  jobs:
    - job: Build
      displayName: Build
      steps:
        - template: templates/checkout-and-cache.yml

        - script: yarn run build
          displayName: 'Build App'
          env:
            NODE_ENV: production
            MONGODB_URI: $(MONGODB_URI)

        - task: ArchiveFiles@2
          displayName: 'Archive Build'
          inputs:
            rootFolderOrFile: .
            includeRootFolder: false
            archiveType: 'tar'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).tar.gz'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).tar.gz'
            ArtifactName: '$(APP_FOLDER_NAME)-artifact'
            publishLocation: 'Container'

        - script: yarn run devops
          displayName: 'Report DevOps Passed'
          env:
            AZ_DEVOPS_DISCORD_WEBHOOK: $(AZ_DEVOPS_DISCORD_WEBHOOK)
            AZ_DEVOPS_TITLE: $(Build.DefinitionName) - $(Build.BuildNumber)
            AZ_DEVOPS_STATUS: $(Agent.JobStatus)
            AZ_DEVOPS_BUILD_URL: $(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)
            AZ_DEVOPS_REQUESTER: $(Build.RequestedFor)
            AZ_DEVOPS_REQUESTER_ID: $(Build.RequestedForId)
            AZ_DEVOPS_QUEUED_BY: $(Build.QueuedBy)
            AZ_DEVOPS_QUEUED_BY_ID: $(Build.QueuedById)

- stage: ReportFailure
  displayName: Report Failure
  condition: or(not(succeeded('Preparation')), not(succeeded('Build')))

  jobs:
    - job: ReportFailure
      displayName: Report Failure

      steps:
        - template: templates/checkout-and-cache.yml

        - script: yarn run devops
          displayName: 'Report Failure'
          env:
            AZ_DEVOPS_DISCORD_WEBHOOK: $(AZ_DEVOPS_DISCORD_WEBHOOK)
            AZ_DEVOPS_TITLE: $(Build.DefinitionName) - $(Build.BuildNumber)
            # https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables-devops-services
            AZ_DEVOPS_STATUS: 'Failed'
            AZ_DEVOPS_BUILD_URL: $(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)
            AZ_DEVOPS_REQUESTER: $(Build.RequestedFor)
            AZ_DEVOPS_REQUESTER_ID: $(Build.RequestedForId)
            AZ_DEVOPS_QUEUED_BY: $(Build.QueuedBy)
            AZ_DEVOPS_QUEUED_BY_ID: $(Build.QueuedById)
